
   - name: install MariaDB - Ubuntu
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "Amazon"


   - name: install mariadb server
     tags: db,mariadb
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"

